development:
  adapter: postgresql
  encoding: unicode
  database: json-rails_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: json-rails_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: json-rails_production
  pool: 5
